# vim: ft=python expandtab
Import('env')
#import os

#env_test = Environment(PDB='parser.pdb', ENV=os.environ)
env_test = env.Clone(PDB='parser.pdb')
env_test.Append(CPPDEFINES=['_DEBUG', ('TEST_SRCDIR', r'\"C:\\Documents and Settings\\zsx\\My Documents\\super-totem\\totem-plparser\\plparse\\tests\\\\\"')])
#env_test.Append(CPPPATH=['#', '#lib', '#plparse'])

env_test.ParseConfig('pkg-config gio-2.0 --cflags --libs')
env_test.ParseConfig('pkg-config gobject-2.0 --cflags --libs')
env_test.ParseConfig('pkg-config gmime --cflags --libs')

env_test_parser = env_test.Clone()
#env_test_parser.Append(LIBS='
env_test_parser.Program('parser', ['parser.c', '#lib/libtotem_glibc.lib', '#plparse/libtotem_plparser.lib'])
