# vim: ft=python expandtab
Import('env')

env_test = env.Clone()
env_test.Append(CPPDEFINES=[('TEST_SRCDIR', r'\"C:\\Documents and Settings\\zsx\\My Documents\\super-totem\\totem-plparser\\plparse\\tests\"')])

env_test.ParseConfig('pkg-config gio-2.0 --libs')
env_test.ParseConfig('pkg-config gobject-2.0 --libs')
env_test.ParseConfig('pkg-config gmime --libs')

env_test_parser = env_test.Clone()
#env_test_parser.Append(LIBS='
env_test_parser.Program('parser', ['parser.c', '#lib/libtotem_glibc.lib', '#plparse/libtotem_plparser.lib'])
